import java.nio.file.Files
import java.util.jar.JarEntry
import java.util.jar.JarFile

plugins() {
	id('net.fabricmc.fabric-loom') version('1.15-SNAPSHOT')
}

version = project.mod_version
group = project.maven_group

base() {
	archivesName = project.archives_base_name
}

sourceSets() {
	main() {
		java() {
			srcDirs = [ file("src/common/java"), file("src/${project.minecraft_version}/java") ]
		}
		resources() {
			srcDirs = [ file("src/common/resources"), file("src/${project.minecraft_version}/resources") ]
		}
	}
	test() {
		java() {
			srcDirs = [ file("src/test/java") ]
		}
		resources() {
			srcDirs = [ file("src/test/resources") ]
		}
	}
}

repositories() {
	maven() {
		url('https://api.modrinth.com/maven')
	}

	//for yacl.
	repositories {
		maven() {
			url("https://maven.isxander.dev/releases")
		}
	}

	//loom does this automatically, but does it too late.
	//we need to ensure this gets added as a repository before
	//all the hacks below that make JIJ dependencies work.
	maven() {
		name = 'MavenCentralLWJGL' //loom checks for this name, so it cannot be changed.
		url(ArtifactRepositoryContainer.MAVEN_CENTRAL_URL)
		content() {
			includeGroup('org.lwjgl')
		}
	}
}

configurations() {
	jijImplementation() {
		canBeResolved = true
	}
	jijRuntimeOnly() {
		canBeResolved = true
	}
	jijCompileOnly() {
		canBeResolved = true
	}
}

static void extractNestedJars(File dependenciesFolder, File toUnpack) {
	try (JarFile jar = new JarFile(toUnpack)) {
		Enumeration<JarEntry> entries = jar.entries()
		while (entries.hasMoreElements()) {
			JarEntry entry = entries.nextElement()
			String name = entry.getName()
			if (name.startsWith('META-INF/jars/') && name.endsWith('.jar') && !name.regionMatches(false, 'META-inf/jars/'.length(), 'fabric-', 0, 'fabric-'.length())) {
				name = name.substring('META-INF/jars/'.length())
				File unpackDir = new File(dependenciesFolder, name.substring(0, name.length() - '.jar'.length()))
				unpackDir.mkdir()
				File unpacked = new File(unpackDir, name)
				try (FileOutputStream out = new FileOutputStream(unpacked)) {
					jar.getInputStream(entry).transferTo(out)
				}
				extractNestedJars(unpackDir, unpacked)
			}
		}
	}
}

void extractDependencies() {
	File jijDependenciesFolder = file('jijDependencies')
	jijDependenciesFolder.deleteDir()
	jijDependenciesFolder.mkdir()
	for (String dependencyType : [ 'implementation', 'runtimeOnly', 'compileOnly' ]) {
		File specificDependenciesFolder = new File(jijDependenciesFolder, dependencyType)
		specificDependenciesFolder.mkdir()
		for (File from : getConfigurations().getByName("jij${ dependencyType.capitalize() }").getResolvedConfiguration().getResolvedArtifacts().file) {
			String fileName = from.getName()
			File fromRoot = new File(specificDependenciesFolder, fileName.substring(0, fileName.length() - '.jar'.length()))
			fromRoot.mkdir()
			File to = new File(fromRoot, fileName)
			if (!to.exists()) {
				Files.copy(from.toPath(), to.toPath())
				extractNestedJars(fromRoot, to)
			}
		}
	}
}

dependencies() {
	minecraft("com.mojang:minecraft:${ project.minecraft_version }")
	implementation("net.fabricmc:fabric-loader:${ project.loader_version }")

	jijImplementation("maven.modrinth:modmenu:${ project.modmenu_version }")
	jijImplementation("dev.isxander:yet-another-config-lib:${ project.yacl_version }") {
		transitive = false
	}
	runtimeOnly("net.fabricmc.fabric-api:fabric-api:${ project.fabric_version }")

	annotationProcessor('systems.manifold:manifold-preprocessor:2025.1.23')

	extractDependencies()
	implementation(fileTree(file('jijDependencies/implementation')))
	compileOnly(fileTree(file('jijDependencies/compileOnly')))
	runtimeOnly(fileTree(file('jijDependencies/runtimeOnly')))

	testImplementation('org.junit.jupiter:junit-jupiter:5.7.1')
	testRuntimeOnly('org.junit.platform:junit-platform-launcher')
}

loom() {
	accessWidenerPath = file("src/${ project.minecraft_version }/resources/fractallightning.accesswidener")
}

int targetJavaVersion = 25
tasks.withType(JavaCompile).configureEach() {
	it.options.encoding = "UTF-8"
}

compileJava() {
	options.compilerArgs.add('-Xplugin:Manifold')
}

java() {
	def javaVersion = JavaVersion.toVersion(targetJavaVersion)
	if (JavaVersion.current() < javaVersion) {
		toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
	}
	withSourcesJar()

	sourceCompatibility = JavaLanguageVersion.of(targetJavaVersion)
	targetCompatibility = JavaLanguageVersion.of(targetJavaVersion)
}

jar() {
	from("LICENSE") {
		rename() { "${ it }_${ project.archives_base_name }" }
	}
}

processResources() {
	inputs.property('version', project.version)
	filteringCharset('UTF-8')

	filesMatching('fabric.mod.json') {
		expand('version': project.version, 'mc_version': project.minecraft_version)
	}
}

tasks.register('copyToReleases', Copy) {
	dependsOn(jar)
	from("$projectDir/build/libs") {
		include("$project.archives_base_name-${ project.version }.jar")
		rename() {
			"$project.archives_base_name-$project.version-MC${ minecraft_version }.jar"
		}
	}
	into(file("releases/${ project.version.toString().replace('.' as char, '/' as char) }"))
}

test() {
	doFirst() {
		if (file("releases/${project.version.toString().replace('.' as char, '/' as char)}/$project.archives_base_name-$project.version-MC${minecraft_version}.jar").exists()) {
			throw new IllegalStateException("Release file $project.version-MC$minecraft_version already exists. If you intend to overwrite this file, delete it first. Otherwise, you probably forgot to bump the version.")
		}
	}
	useJUnitPlatform()
}

build() {
	dependsOn(copyToReleases)
}

class Version {

	int year, drop, fix

	Version(int year, int drop, int fix) {
		this.year = year
		this.drop = drop
		this.fix = fix
	}

	static String pad(int number) {
		return number < 10 ? "0$number" : number.toString()
	}

	String shorthand() {
		return "${year}${pad(drop)}${pad(fix)}"
	}

	String longhand() {
		return this.fix == 0 ? "${year}.${drop}" : "${year}.${drop}.${fix}"
	}
}

Collection<Map.Entry<String, String>> loadProperties(String fileName) {
	Properties properties = new Properties()
	try (InputStream stream = new FileInputStream(file(fileName))) {
		properties.load(stream)
	}
	return properties.entrySet()
}

Map<String, String> loadVersion(Version version) {
	return (
		new HashMap<String, String>()
		.putAll(loadProperties('gradle_common.properties'))
		.putAll(loadProperties("gradle_${version.longhand()}.properties"))
	)
}

tasks.register("Currently V$project.version for MC $project.minecraft_version") {
	group('versions')
	doFirst() {
		println("Currently V$project.version for MC $project.minecraft_version")
	}
}

for (Version version in [
	new Version(26, 1, 0),
	new Version(26, 2, 0),
	new Version(26, 3, 0)
]) {
	Version capturedVersion = version
	tasks.register("Switch to ${capturedVersion.longhand()}", WriteProperties) {
		group('versions')
		destinationFile = file('gradle.properties')
		comment('This file was automatically generated by gradle. Do not touch!')
		properties(loadVersion(capturedVersion))
		doLast() {
			file('build.properties').text = (
			"""#This file was automatically generated by gradle. Do not touch!
MC_26_1_0=260100
MC_26_2_0=260200
MC_26_3_0=260300
MC_VERSION=${capturedVersion.shorthand()}"""
			)
		}
	}
}